version: '3.9'
services:
  controlnet-queue-worker:
    container_name: controlnet-preprocessor-queue-worker
    image: controlnet-preprocessor-queue-worker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
      S3_ENDPOINT: http://localstack-s3-sqs:4566
      SQS_ENDPOINT: http://localstack-s3-sqs:4566
      PREPROCESSOR_SERVER_URL: https://smoky-tamarind-garden.salad.cloud
      SALAD_API_KEY: ${SALAD_API_KEY}
      QUEUE_URL: http://localstack-s3-sqs:4566/000000000000/controlnet-preprocessor-jobs.fifo
      JOB_TABLE: test-table
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      # There's a bunch of keys in the fixtures folder that we need to use
      - type: bind
        source: ./test/fixtures
        target: /app/test/fixtures
        read_only: true
  localstack:
    container_name: "localstack-s3-sqs"
    image: localstack/localstack:2.0.1
    ports:
      - "4566:4566" # LocalStack Gateway
      # - "4571:4571" # external services port range
    environment:
      DEBUG: ${DEBUG-}
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: s3,sqs
      START_WEB: 0
      PROVIDER_OVERRIDE_S3: v2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal